_wandb:
    value:
        cli_version: 0.21.3
        e:
            obvzp4icejoh6ftg24vmm2o9epd94jpa:
                args:
                    - -s
                    - -vv
                    - .
                    - --reference_artifact
                    - exercise_14/preprocessed_data.csv:latest
                    - --sample_artifact
                    - exercise_5/preprocessed_data.csv:latest
                    - --ks_alpha
                    - "0.05"
                cpu_count: 7
                cpu_count_logical: 14
                disk:
                    /:
                        total: "1081101176832"
                        used: "19212808192"
                email: dallas.taylor96@outlook.com
                executable: /home/dtay_dev/miniconda3/envs/mlflow-8b8c5bbbcf30a4f621fb194c7af489e467ffbbf1/bin/python3.13
                git:
                    commit: b127fbbaf56b52af74b95dcd289eda99425795dd
                    remote: https://github.com/de-taylor/d501-wgu.git
                host: DET-WS
                memory:
                    total: "8039104512"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/dtay_dev/miniconda3/envs/mlflow-8b8c5bbbcf30a4f621fb194c7af489e467ffbbf1/bin/pytest
                python: CPython 3.13.9
                root: /home/dtay_dev/d501/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/check_data
                startedAt: "2025-10-21T18:07:16.268100Z"
                writerId: obvzp4icejoh6ftg24vmm2o9epd94jpa
        m: []
        python_version: 3.13.9
        t:
            "4": 3.13.9
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
